version: '3.1'

services:
  mysql8-container:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # This is just for the root user; consider changing it from 'password'
      MYSQL_DATABASE: twitter-clone
      MYSQL_USER: twitterclone
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
